name: mindful_pluto_grid_util
description: "flutter_package for Flutter utilities that work with pluto_grid"
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_shimmer: ^2.1.2
  pluto_grid: ^6.0.4
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1
